// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.Infrastructure.Persistence.DbContexts;

#nullable disable

namespace TaskManagement.Infrastructure.Persistence.Migrations.Log
{
    [DbContext(typeof(LogDbContext))]
    partial class LogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Domin.Entities.LogEntities.EntityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Action")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(6)")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint");

                    b.Property<string>("LogDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("EntityLogs");
                });

            modelBuilder.Entity("TaskManagement.Domin.Entities.LogEntities.EntityRelationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Action")
                        .HasColumnType("tinyint");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(6)")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LogDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PrimaryEntityId")
                        .HasColumnType("int");

                    b.Property<byte>("PrimaryEntityType")
                        .HasColumnType("tinyint");

                    b.Property<int>("SecondaryEntityId")
                        .HasColumnType("int");

                    b.Property<byte>("SecondaryEntityType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryEntityId", "SecondaryEntityId", "PrimaryEntityType", "SecondaryEntityType");

                    b.ToTable("EntityRelationLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
