<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTOs\**" />
    <Compile Remove="Filters\**" />
    <Compile Remove="Middlewares\**" />
    <EmbeddedResource Remove="DTOs\**" />
    <EmbeddedResource Remove="Filters\**" />
    <EmbeddedResource Remove="Middlewares\**" />
    <None Remove="DTOs\**" />
    <None Remove="Filters\**" />
    <None Remove="Middlewares\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManagement.Infrastructure\TaskManagement.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.13" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

</Project>
