<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\Services\Log\**" />
    <Compile Remove="Services\Log\**" />
    <EmbeddedResource Remove="Interfaces\Services\Log\**" />
    <EmbeddedResource Remove="Services\Log\**" />
    <None Remove="Interfaces\Services\Log\**" />
    <None Remove="Services\Log\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManagement.Domain\TaskManagement.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

</Project>
